# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/task: pointnav
  - /habitat/dataset/pointnav: habitat_test
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: rgbds_agent
  - _self_

habitat:
  environment:
    max_episode_steps: 500
  simulator:
    type: Unreal-Simulator-v0
    agents:
      main_agent:
        height: 2.0
        radius: 0.5
        sim_sensors:
          rgb_sensor:
            width: 640
            height: 480
            type: UnrealRGBSensor
          depth_sensor:
            width: 640
            height: 480
            type: UnrealDepthSensor
          semantic_sensor:
            width: 640
            height: 480
            type: UnrealSemanticSensor
    forward_step_size: 0.25
    turn_angle: 15
    step_physics: False
    unreal_config:
      max_slope: 25.0
      max_step_height: 30.0

