# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/task: pointnav
  - /habitat/dataset/pointnav: habitat_test
  - /habitat/simulator/sensor_setups@habitat.simulator.agents.main_agent: rgbd_agent
  - _self_

habitat:
  seed: 101 #not implemented yet
  #env_task: UnrealEnv
  environment:
    max_episode_steps: 500
  task:
    spawn_max_dist_to_obj: 10.0
  dataset:
 #   type: PointNav-v1
   data_path: data/datasets/pointnav/unreal-scenes/{split}/dataset.json.gz
  simulator:
    type: Unreal-Simulator-v0
    scene: UE5
    agents:
      main_agent:
        height: 1.80
        radius: 0.25
        max_climb: 0.2 #meters
        max_slope: 25.0 #degrees
        sim_sensors:
          rgb_sensor:
            width: 640
            height: 480
            type: UnrealRGBSensor
            hfov: 90
          depth_sensor:
            width: 640
            height: 480
            type: UnrealDepthSensor
            hfov: 90
            max_depth: 20.0
            min_depth: 0.0 #always 0.0, don't change
            normalize_depth: True #always True, don't change
          #semantic_sensor:
          #  width: 640
          #  height: 480
          #  type: UnrealSemanticSensor
          #  hfov: 90
    forward_step_size: 0.25
    turn_angle: 15
    step_physics: False
    #no longer needed? keep around in case we need to add a new set of custom settings?
    #unreal_config:
    #  max_slope: 25.0
    #  max_step_height: 30.0

